### ISSUE TITLE
bugsinho

### ISSUE THREAD

**Issue by splaint** [matheusfelipeog/knight-game-appinventor#1]
e ai...i olha soh não sei se já arrumou mas eu notei que quando tu fica pulando o coração vai junto na imagem, dai não vai conseguir pegar.. so andando mesmo... blzz..

**Comment by matheusfelipeog** [comment]
Obrigado pela colaboração, o bug será corrigido na próxima atualização que está prestes a acontecer

**Comment by matheusfelipeog** [comment]
Obrigado pela colaboração, o bug será corrigido na próxima atualização, assim como outros encontrados

**Comment by matheusfelipeog** [comment]
Bug resolvido 👍
